- hosts: web
  tasks:
    - name: create directory
      file:
         path: /tmp/data
         state: directory

    - copy:
          content: "jenkins intregration"
          dest: /tmp/data/abc.txt
